# About Series

In [1]:
import pandas as pd

In [ ]:
ls1 = [1,2,3,4,5,6,7,8,9]

sr1 = pd.Series(ls1)
sr1

In [5]:
ls2 = [1,2,3,'Apple','play',6,7,8,9]

sr2 = pd.Series(ls2)
sr2

0        1
1        2
2        3
3    Apple
4     play
5        6
6        7
7        8
8        9
dtype: object

## Series에 Name설정

In [47]:
import pandas as pd

In [49]:

path = 'C:/Users/proyj/workspace/python/pandas/삼성전자 종가.csv'

seriess = pd.read_csv(path, index_col = 0, header = 0)
seriess




Close
Date             
2018-01-02  51020
2018-01-03  51620
2018-01-04  51080
2018-01-05  52120
2018-01-08  52020
...           ...
2021-12-13  76800
2021-12-14  77000
2021-12-15  77600
2021-12-16  77800
2021-12-17  78000

[977 rows x 1 columns]

```squeeze = True``` 추가 하지 않으면 DataFrame이 된다.

In [50]:
a = pd.read_csv(path, index_col = 0, squeeze = True, header = 0)

a

C:\Users\proyj\AppData\Local\Temp\ipykernel_15960\1169558850.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  a = pd.read_csv(path, index_col = 0, squeeze = True, header = 0)


Date
2018-01-02    51020
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...  
2021-12-13    76800
2021-12-14    77000
2021-12-15    77600
2021-12-16    77800
2021-12-17    78000
Name: Close, Length: 977, dtype: int64

In [13]:
# Series의 index 포함 여부 확인
'2018-01-02' in samsung_series.index

True

In [11]:
samsung_series = a

# Series의 index들 얻기
samsung_series.index


Index(['2018-01-02', '2018-01-03', '2018-01-04', '2018-01-05', '2018-01-08',
       '2018-01-09', '2018-01-10', '2018-01-11', '2018-01-12', '2018-01-15',
       ...
       '2021-12-06', '2021-12-07', '2021-12-08', '2021-12-09', '2021-12-10',
       '2021-12-13', '2021-12-14', '2021-12-15', '2021-12-16', '2021-12-17'],
      dtype='object', name='Date', length=977)

In [14]:
# Series의 index 포함 여부 확인
'2018-01-01' in samsung_series.index

False

In [13]:
# Series의 index 포함 여부 확인
'2018-01-02' in samsung_series.index

True

## Series에서 찾기

### 값으로 찾기

In [25]:
# 값으로 찾기
samsung_series.loc['2018-01-01']

KeyError: '2018-01-01'

In [17]:
samsung_series.loc['2018-01-02']

51020

In [24]:
# 예제

date = '2018-01-01'
if date in samsung_series.index:
    print(samsung_series.loc[date])
else:
    print('찾는 값이 없습니다.')
        

찾는 값이 없습니다.


### 인덱스로 찾기

In [23]:
#index로 찾기
samsung_series.iloc[0]

51020

## Series의 크기

***samsung_series.shape***

In [27]:
samsung_series.shape

(977,)

그런데 형태가 좀 이상하다..

In [28]:
type(samsung_series.shape)

tuple

마지막 인덱스 구하는 방법

In [29]:
samsung_series.shape[0]-1

976

다음 3가지로 쓴다  
series.['2018-01-01'] (가능은 하지만 아래와 같이 명시적으로 써 주는게 좋다)  
series.log['2018-01-01']   
series.ilog[1]


In [34]:
# 값 변경
samsung_series.loc['2018-01-02'] = 0
samsung_series

Date
2018-01-02        0
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...  
2021-12-13    76800
2021-12-14    77000
2021-12-15    77600
2021-12-16    77800
2021-12-17    78000
Name: Close, Length: 977, dtype: int64

In [37]:
## 값 추가
samsung_series.iloc(samsung_series.shape[0]) = 77100

SyntaxError: cannot assign to function call (773930455.py, line 2)

In [40]:
## 값 추가
samsung_series['2021-12-18'] = 77100
samsung_series

Date
2018-01-02        0
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...  
2021-12-14    77000
2021-12-15    77600
2021-12-16    77800
2021-12-17    78000
2021-12-18    77100
Name: Close, Length: 978, dtype: int64

In [41]:
samsung_series.loc['2021-12-19'] = 77200
samsung_series

Date
2018-01-02        0
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...  
2021-12-15    77600
2021-12-16    77800
2021-12-17    78000
2021-12-18    77100
2021-12-19    77200
Name: Close, Length: 979, dtype: int64

In [46]:
samsung_series.iloc[978] = 77300
samsung_series

Date
2018-01-02        0
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...  
2021-12-15    77600
2021-12-16    77800
2021-12-17    78000
2021-12-18    77100
2021-12-19    77300
Name: Close, Length: 979, dtype: int64

## 두개의 Series 연결



In [51]:
import pandas as pd
#pd.set_option('display.max_rows', None)

In [52]:
series1_samsung = pd.read_excel('samsung_excel.xlsx', sheet_name = 'Sheet1', index_col = 0, squeeze = True)
series1_samsung

C:\Users\proyj\AppData\Local\Temp\ipykernel_15960\3120514832.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  series1_samsung = pd.read_excel('samsung_excel.xlsx', sheet_name = 'Sheet1', index_col = 0, squeeze = True)


Date
2018-01-02    51020
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...  
2019-12-23    55500
2019-12-24    55000
2019-12-26    55400
2019-12-27    56500
2019-12-30    55800
Name: Close, Length: 490, dtype: int64

```sheet_name = 0``` 이라고 할 수도 있음

In [59]:
series2_samsung = pd.read_excel('samsung_excel.xlsx', sheet_name = 'Sheet2', index_col = 0, squeeze = True)
series2_samsung

C:\Users\proyj\AppData\Local\Temp\ipykernel_15960\969072097.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  series2_samsung = pd.read_excel('samsung_excel.xlsx', sheet_name = 'Sheet2', index_col = 0, squeeze = True)


Date
2020-01-02    55200
2020-01-03    55500
2020-01-06    55500
2020-01-07    55800
2020-01-08    56800
2020-01-09    58600
2020-01-10    59500
2020-01-13    60000
2020-01-14    60000
2020-01-15    59000
2020-01-16    60700
2020-01-17    61300
2020-01-20    62400
2020-01-21    61400
2020-01-22    62300
2020-01-23    60800
2020-01-28    58800
2020-01-29    59100
2020-01-30    57200
2020-01-31    56400
2020-02-03    57200
2020-02-04    58900
2020-02-05    59500
2020-02-06    61100
2020-02-07    60400
2020-02-10    59700
2020-02-11    59900
2020-02-12    60500
2020-02-13    60700
2020-02-14    61800
2020-02-17    61500
2020-02-18    59800
2020-02-19    60200
2020-02-20    60000
2020-02-21    59200
2020-02-24    56800
2020-02-25    57900
2020-02-26    56500
2020-02-27    55900
2020-02-28    54200
2020-03-02    55000
2020-03-03    55400
2020-03-04    57400
2020-03-05    57800
2020-03-06    56500
2020-03-09    54200
2020-03-10    54600
2020-03-11    52100
2020-03-12    50800
2020-03-13    4

In [60]:
# output 을 전체 다 볼 수 있음
pd.set_option('display.max_rows', None)

In [63]:
series_samsung = series1_samsung.append(series2_samsung, ignore_index = False)
series_samsung

C:\Users\proyj\AppData\Local\Temp\ipykernel_15960\1297777962.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  series_samsung = series1_samsung.append(series2_samsung, ignore_index = False)


Date
2018-01-02    51020
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
2018-01-09    50400
2018-01-10    48840
2018-01-11    48240
2018-01-12    48200
2018-01-15    48540
2018-01-16    50000
2018-01-17    49620
2018-01-18    49900
2018-01-19    49320
2018-01-22    48240
2018-01-23    49160
2018-01-24    49340
2018-01-25    50260
2018-01-26    50780
2018-01-29    51220
2018-01-30    49800
2018-01-31    49900
2018-02-01    49820
2018-02-02    47700
2018-02-05    47920
2018-02-06    47420
2018-02-07    45800
2018-02-08    46000
2018-02-09    44700
2018-02-12    45720
2018-02-13    47540
2018-02-14    49000
2018-02-19    48380
2018-02-20    47400
2018-02-21    47280
2018-02-22    46760
2018-02-23    47220
2018-02-26    47380
2018-02-27    47380
2018-02-28    47060
2018-03-02    46020
2018-03-05    45200
2018-03-06    47020
2018-03-07    48620
2018-03-08    49200
2018-03-09    49740
2018-03-12    49740
2018-03-13    51660
2018-03-14    51760
2018-03-15    5

```ignore_index = False``` # False: 기존 index 유지, True: 기존 index 무시

## Series 기본 통계치 구하기

In [65]:
# option default로 변경
pd.reset_option("display.max_rows")

In [66]:
samsung_price = pd.read_csv('삼성전자 종가.csv', index_col = 0, squeeze = True, header = 0)
samsung_price

C:\Users\proyj\AppData\Local\Temp\ipykernel_15960\3135519495.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  samsung_price = pd.read_csv('삼성전자 종가.csv', index_col = 0, squeeze = True, header = 0)


Date
2018-01-02    51020
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...  
2021-12-13    76800
2021-12-14    77000
2021-12-15    77600
2021-12-16    77800
2021-12-17    78000
Name: Close, Length: 977, dtype: int64

In [67]:
# 최고값
samsung_price.max()

91000

In [68]:
# 최저값
samsung_price.min()

37450

In [69]:
# 기본 통계치
samsung_price.describe()


count      977.000000
mean     57295.854657
std      14084.402274
min      37450.000000
25%      46300.000000
50%      51300.000000
75%      70200.000000
max      91000.000000
Name: Close, dtype: float64

### 최고값일때의 날짜는 언제일까?

***생각의 과정***  
처음에는 배열을 비교하여 최고값의 개수를

In [73]:
samsung_price.values

array([51020, 51620, 51080, 52120, 52020, 50400, 48840, 48240, 48200,
       48540, 50000, 49620, 49900, 49320, 48240, 49160, 49340, 50260,
       50780, 51220, 49800, 49900, 49820, 47700, 47920, 47420, 45800,
       46000, 44700, 45720, 47540, 49000, 48380, 47400, 47280, 46760,
       47220, 47380, 47380, 47060, 46020, 45200, 47020, 48620, 49200,
       49740, 49740, 51660, 51760, 51540, 51140, 50740, 51200, 51060,
       51780, 49720, 50280, 49980, 48700, 49040, 49220, 48540, 48120,
       46920, 48740, 48400, 49200, 48880, 48860, 49000, 49800, 50340,
       49980, 51360, 52780, 51620, 51900, 50460, 50400, 52140, 53000,
       53000, 53000, 53000, 51900, 52600, 50900, 51600, 51300, 50100,
       49200, 49850, 49400, 49500, 50000, 51800, 51400, 52700, 52300,
       51300, 49500, 50700, 51300, 51100, 51300, 50600, 49650, 49900,
       49400, 48200, 47650, 46600, 47000, 47000, 47050, 47250, 46650,
       47000, 47950, 46800, 46650, 45550, 46150, 46250, 45950, 44900,
       45600, 46300,

In [75]:
type(samsung_price.values)

numpy.ndarray

In [74]:
samsung_price.values == samsung_price.max()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [76]:
samsung_price.index[samsung_price.values == samsung_price.max()]

Index(['2021-01-11'], dtype='object', name='Date')

해당하는 인덱스 배열을 리턴해 준다.

In [79]:
samsung_price.values == 41000

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [78]:
samsung_price.index[samsung_price.values == 41000]

Index(['2018-10-25', '2018-10-26'], dtype='object', name='Date')

### 인덱스 리턴

In [81]:
## 해당하는 인덱스 값 리턴
samsung_price.argmin()

246

cf. samsung_price.min() => 최소값, samsung_price.argmin() => 최소값의 인덱스

In [83]:
samsung_price.iloc[samsung_price.argmin()]

37450

In [84]:
samsung_price.index[samsung_price.argmin()]

'2019-01-04'

In [85]:
samsung_price.iloc[samsung_price.argmax()]
samsung_price.index[samsung_price.argmax()]

'2021-01-11'